---

- hosts: all
  become: true
  tasks:

          - name: update repository index
            apt:
                    update_cache: yes
            when: ansible_distribution == "Ubuntu"

          - name: install mysql server
            apt:
                    name: mysql-server
                    state: latest
            when: ansible_distribution == "Ubuntu"
